<section class="benefits-section">
  <h2 class="benefits-title">
    <span data-translate="benefits-title">Почему</span>
    <span class="span-benefits-title" data-translate="span-benefits-title">выбирают нас</span>
  </h2>
  <div class="benefits-containers">
    <div class="benefits-container">
      <div class="benefits-top">
        <p class="benefits-number">1</p>
        <p class="benefits-top-text" data-translate="benefits-top-text1">ПОРЯДОЧНОСТЬ</p>
      </div>
      <picture>
        <source srcset="./src/img/bene-1.webp" type="image/webp" />
        <img
          class="benefits-img"
          src="./src/img/bene-1.jpg"
          alt="porjadnist"
          loading="lazy"
        />
      </picture>
      <p class="benefits-bot-text" data-translate="benefits-bot-text1">
        «Честныи ремонт: только нужные работы, только нужные запчасти.»
      </p>
    </div>
    <div class="benefits-container">
      <div class="benefits-top">
        <p class="benefits-number">2</p>
        <p class="benefits-top-text" data-translate="benefits-top-text2">ОТВЕТСТВЕННОСТЬ</p>
      </div>
      <picture>
        <source srcset="./src/img/bene-2.webp" type="image/webp" />
        <img
          class="benefits-img"
          src="./src/img/bene-2.jpg"
          alt="vidpovidalnist"
          loading="lazy"
        />
      </picture>
      <p class="benefits-bot-text" data-translate="benefits-bot-text2">
        «Гарантируем качество – отвечаем за результат!»
      </p>
    </div>
    <div class="benefits-container">
      <div class="benefits-top">
        <p class="benefits-number">3</p>
        <p class="benefits-top-text" data-translate="benefits-top-text3">ОПЕРАТИВНОСТЬ</p>
      </div>
      <picture>
        <source srcset="./src/img/bene-3.webp" type="image/webp" />
        <img
          class="benefits-img"
          src="./src/img/bene-3.jpg"
          alt="operatyvnist"
          loading="lazy"
        />
      </picture>
      <p class="benefits-bot-text" data-translate="benefits-bot-text3">
        «Ваше авто не задержится у нас дольше необходимого.»
      </p>
    </div>
  </div>
</section>
