<section id="brend" class="brend-section">
          <h2 class="brend-title" data-translate="brend-title">
            СТО в Павлограде
          </h2>
          <div class="infinite-carousel">
            <div class="carousel-track">
              <div>
                <picture>
                  <source
                    srcset="./src/img/avto-logo/4226-256x256x8.webp"
                    type="image/webp"
                  />
                  <img
                    src="./src/img/avto-logo/4226-256x256x8.png"
                   
                    loading="lazy"
                    data-brand="daewoo"
                    alt=""
                  />
                </picture>
                <p class="text-brend">daewoo</p>
              </div>
              <div>
                <picture>
                  <source
                    srcset="./src/img/avto-logo/4227-256x256x32.webp"
                    type="image/webp"
                  />
                  <img
                    src="./src/img/avto-logo/4227-256x256x32.png"
                   
                    loading="lazy"
                    data-brand="daihatsu"
                    alt=""
                  />
                </picture>
                <p class="text-brend">daihatsu</p>
              </div>
              <div>
                <picture>
                  <source
                    srcset="./src/img/avto-logo/acura_logo.webp"
                    type="image/webp"
                  />
                  <img
                    src="./src/img/avto-logo/acura_logo.png"
                   
                    loading="lazy"
                    data-brand="acura"
                    alt=""
                  />
                </picture>
                <p class="text-brend">acura</p>
              </div>
              <div>
                <picture>
                  <source
                    srcset="./src/img/avto-logo/alfa-romeo-logo.webp"
                    type="image/webp"
                  />
                  <img
                    src="./src/img/avto-logo/alfa-romeo-logo.png"
                   
                    loading="lazy"
                    data-brand="alfa-romeo"
                    alt=""
                  />
                </picture>
                <p class="text-brend">alfa-romeo</p>
              </div>
              <div>
                <picture>
                  <source
                    srcset="./src/img/avto-logo/audi.webp"
                    type="image/webp"
                  />
                  <img
                    src="./src/img/avto-logo/audi.png"
                   
                    loading="lazy"
                    data-brand="audi"
                    alt=""
                  />
                </picture>
                <p class="text-brend">audi</p>
              </div>
              <div>
                <picture>
                  <source
                    srcset="./src/img/avto-logo/chevrolet-logo.webp"
                    type="image/webp"
                  />
                  <img
                    src="./src/img/avto-logo/chevrolet-logo.png"
                   
                    loading="lazy"
                    data-brand="chevrolet"
                    alt=""
                  />
                </picture>
                <p class="text-brend">chevrolet</p>
              </div>
              <div>
                <picture>
                  <source
                    srcset="./src/img/avto-logo/daewoo-logo.webp"
                    type="image/webp"
                  />
                  <img
                    src="./src/img/avto-logo/daewoo-logo.png"
                   
                    loading="lazy"
                    data-brand="daewoo"
                    alt=""
                  />
                </picture>
                <p class="text-brend">daewoo</p>
              </div>
              <div>
                <picture>
                  <source
                    srcset="./src/img/avto-logo/citroen-logo.webp"
                    type="image/webp"
                  />
                  <img
                    src="./src/img/avto-logo/citroen-logo.jpg"
                   
                    loading="lazy"
                    data-brand="citroen"
                    alt=""
                  />
                </picture>
                <p class="text-brend">citroen</p>
              </div>
              <div>
                <picture>
                  <source
                    srcset="./src/img/avto-logo/dodge-logo.webp"
                    type="image/webp"
                  />
                  <img
                    src="./src/img/avto-logo/dodge-logo.png"
                   
                    loading="lazy"
                    data-brand="dodge"
                    alt=""
                  />
                </picture>
                <p class="text-brend">dodge</p>
              </div>
              <div>
                <picture>
                  <source
                    srcset="./src/img/avto-logo/fiat_logo.webp"
                    type="image/webp"
                  />
                  <img
                    src="./src/img/avto-logo/fiat_logo.png"
                   
                    loading="lazy"
                    data-brand="fiat"
                    alt=""
                  />
                </picture>
                <p class="text-brend">fiat</p>
              </div>
              <div>
                <picture>
                  <source
                    srcset="./src/img/avto-logo/ford.webp"
                    type="image/webp"
                  />
                  <img
                    src="./src/img/avto-logo/ford.png"
                   
                    loading="lazy"
                    data-brand="ford"
                    alt=""
                  />
                </picture>
                <p class="text-brend">ford</p>
              </div>
              <div>
                <picture>
                  <source
                    srcset="./src/img/avto-logo/honda-color-128.webp"
                    type="image/webp"
                  />
                  <img
                    src="./src/img/avto-logo/honda-color-128.png"
                   
                    loading="lazy"
                    data-brand="honda"
                    alt=""
                  />
                </picture>
                <p class="text-brend">honda</p>
              </div>
              <div>
                <picture>
                  <source
                    srcset="./src/img/avto-logo/hyundai-lg.webp"
                    type="image/webp"
                  />
                  <img
                    src="./src/img/avto-logo/hyundai-lg.png"
                   
                    loading="lazy"
                    data-brand="hyundai"
                    alt=""
                  />
                </picture>
                <p class="text-brend">hyundai</p>
              </div>
              <div>
                <picture>
                  <source
                    srcset="./src/img/avto-logo/infiniti.webp"
                    type="image/webp"
                  />
                  <img
                    src="./src/img/avto-logo/infiniti.png"
                   
                    loading="lazy"
                    data-brand="infiniti"
                    alt=""
                  />
                </picture>
                <p class="text-brend">infiniti</p>
              </div>
              <div>
                <picture>
                  <source
                    srcset="./src/img/avto-logo/jaguar-logo.webp"
                    type="image/webp"
                  />
                  <img
                    src="./src/img/avto-logo/jaguar-logo.png"
                   
                    loading="lazy"
                    data-brand="jaguar"
                    alt=""
                  />
                </picture>
                <p class="text-brend">jaguar</p>
              </div>
              <div>
                <picture>
                  <source
                    srcset="./src/img/avto-logo/jeep-logo.webp"
                    type="image/webp"
                  />
                  <img
                    src="./src/img/avto-logo/jeep-logo.png"
                   
                    loading="lazy"
                    data-brand="jeep"
                    alt=""
                  />
                </picture>
                <p class="text-brend">jeep</p>
              </div>
              <div>
                <picture>
                  <source
                    srcset="./src/img/avto-logo/kia_logo_256_003.webp"
                    type="image/webp"
                  />
                  <img
                    src="./src/img/avto-logo/kia_logo_256_003.png"
                   
                    loading="lazy"
                    data-brand="kia"
                    alt=""
                  />
                </picture>
                <p class="text-brend">kia</p>
              </div>
              <div>
                <picture>
                  <source
                    srcset="./src/img/avto-logo/land-rover1.webp"
                    type="image/webp"
                  />
                  <img
                    src="./src/img/avto-logo/land-rover1.png"
                   
                    loading="lazy"
                    data-brand="land-rover"
                    alt=""
                  />
                </picture>
                <p class="text-brend">land-rover</p>
              </div>
              <div>
                <picture>
                  <source
                    srcset="./src/img/avto-logo/lexus-logo.webp"
                    type="image/webp"
                  />
                  <img
                    src="./src/img/avto-logo/lexus-logo.png"
                   
                    loading="lazy"
                    data-brand="lexus"
                    alt=""
                  />
                </picture>
                <p class="text-brend">lexus</p>
              </div>
              <div>
                <picture>
                  <source
                    srcset="./src/img/avto-logo/lincoln-logo.webp"
                    type="image/webp"
                  />
                  <img
                    src="./src/img/avto-logo/lincoln-logo.png"
                   
                    loading="lazy"
                    data-brand="lincoln"
                    alt=""
                  />
                </picture>
                <p class="text-brend">lincoln</p>
              </div>
              <div>
                <picture>
                  <source
                    srcset="./src/img/avto-logo/logo_suzuki.webp"
                    type="image/webp"
                  />
                  <img
                    src="./src/img/avto-logo/logo_suzuki.png"
                   
                    loading="lazy"
                    data-brand="suzuki"
                    alt=""
                  />
                </picture>
                <p class="text-brend">suzuki</p>
              </div>
              <div>
                <picture>
                  <source
                    srcset="
                      src/img/avto-logo/mazda_logo_icon_by_mahesh69a-d473lkv.webp
                    "
                    type="image/webp"
                  />
                  <img
                    src="./src/img/avto-logo/mazda_logo_icon_by_mahesh69a-d473lkv.png"
                   
                    loading="lazy"
                    data-brand="mazda"
                    alt=""
                  />
                </picture>
                <p class="text-brend">mazda</p>
              </div>
              <div>
                <picture>
                  <source
                    srcset="./src/img/avto-logo/mercedes_logo.webp"
                    type="image/webp"
                  />
                  <img
                    src="./src/img/avto-logo/mercedes_logo.png"
                   
                    loading="lazy"
                    data-brand="mercedes"
                    alt=""
                  />
                </picture>
                <p class="text-brend">mercedes</p>
              </div>
              <div>
                <picture>
                  <source
                    srcset="./src/img/avto-logo/mitsubishi_logo.webp"
                    type="image/webp"
                  />
                  <img
                    src="./src/img/avto-logo/mitsubishi_logo.png"
                   
                    loading="lazy"
                    data-brand="mitsubishi"
                    alt=""
                  />
                </picture>
                <p class="text-brend">mitsubishi</p>
              </div>
              <div>
                <picture>
                  <source
                    srcset="./src/img/avto-logo/nissan-logo-4.webp"
                    type="image/webp"
                  />
                  <img
                    src="./src/img/avto-logo/nissan-logo-4.png"
                   
                    loading="lazy"
                    data-brand="nissan"
                    alt=""
                  />
                </picture>
                <p class="text-brend">nissan</p>
              </div>
              <div>
                <picture>
                  <source
                    srcset="./src/img/avto-logo/novosti-skoda-logo.webp"
                    type="image/webp"
                  />
                  <img
                    src="./src/img/avto-logo/novosti-skoda-logo.gif"
                   
                    loading="lazy"
                    data-brand="skoda"
                    alt=""
                  />
                </picture>
                <p class="text-brend">skoda</p>
              </div>
              <div>
                <picture>
                  <source
                    srcset="
                      src/img/avto-logo/opel-vectorlogo-dot-biz-128x128-1.webp
                    "
                    type="image/webp"
                  />
                  <img
                    src="./src/img/avto-logo/opel-vectorlogo-dot-biz-128x128-1.png"
                   
                    loading="lazy"
                    data-brand="opel"
                    alt=""
                  />
                </picture>
                <p class="text-brend">opel</p>
              </div>
              <div>
                <picture>
                  <source
                    srcset="./src/img/avto-logo/peugeot_logo_128.webp"
                    type="image/webp"
                  />
                  <img
                    src="./src/img/avto-logo/peugeot_logo_128.png"
                   
                    loading="lazy"
                    data-brand="peugeot"
                    alt=""
                  />
                </picture>
                <p class="text-brend">peugeot</p>
              </div>
              <div>
                <picture>
                  <source
                    srcset="./src/img/avto-logo/renault_logo.webp"
                    type="image/webp"
                  />
                  <img
                    src="./src/img/avto-logo/renault_logo.png"
                   
                    loading="lazy"
                    data-brand="renault"
                    alt=""
                  />
                </picture>
                <p class="text-brend">renault</p>
              </div>
              <div>
                <picture>
                  <source
                    srcset="./src/img/avto-logo/saab-logo.webp"
                    type="image/webp"
                  />
                  <img
                    src="./src/img/avto-logo/saab-logo.png"
                   
                    loading="lazy"
                    data-brand="saab"
                    alt=""
                  />
                </picture>
                <p class="text-brend">saab</p>
              </div>
              <div>
                <picture>
                  <source
                    srcset="./src/img/avto-logo/seat.webp"
                    type="image/webp"
                  />
                  <img
                    src="./src/img/avto-logo/seat.png"
                   
                    loading="lazy"
                    data-brand="seat"
                    alt=""
                  />
                </picture>
                <p class="text-brend">seat</p>
              </div>
              <div>
                <picture>
                  <source
                    srcset="./src/img/avto-logo/smart-logo.webp"
                    type="image/webp"
                  />
                  <img
                    src="./src/img/avto-logo/smart-logo.png"
                   
                    loading="lazy"
                    data-brand="smart"
                    alt=""
                  />
                </picture>
                <p class="text-brend">smart</p>
              </div>
              <div>
                <picture>
                  <source
                    srcset="./src/img/avto-logo/ssangyong-logo.webp"
                    type="image/webp"
                  />
                  <img
                    src="./src/img/avto-logo/ssangyong-logo.png"
                   
                    loading="lazy"
                    data-brand="ssangyong"
                    alt=""
                  />
                </picture>
                <p class="text-brend">ssangyong</p>
              </div>
              <div>
                <picture>
                  <source
                    srcset="./src/img/avto-logo/subaru-logo-transparent.webp"
                    type="image/webp"
                  />
                  <img
                    src="./src/img/avto-logo/subaru-logo-transparent.png"
                   
                    loading="lazy"
                    data-brand="subaru"
                    alt=""
                  />
                </picture>
                <p class="text-brend">subaru</p>
              </div>
              <div>
                <picture>
                  <source
                    srcset="./src/img/avto-logo/toyota.webp"
                    type="image/webp"
                  />
                  <img
                    src="./src/img/avto-logo/toyota.png"
                   
                    loading="lazy"
                    data-brand="toyota"
                    alt=""
                  />
                </picture>
                <p class="text-brend">toyota</p>
              </div>
              <div>
                <picture>
                  <source
                    srcset="./src/img/avto-logo/volkswagen_logo.webp"
                    type="image/webp"
                  />
                  <img
                    src="./src/img/avto-logo/volkswagen_logo.png"
                   
                    loading="lazy"
                    data-brand="volkswagen"
                    alt=""
                  />
                </picture>
                <p class="text-brend">volkswagen</p>
              </div>
            </div>
          </div>
        </section>
